version: 0.1.{build}

install:
  - cmd: nuget restore MissionPlannerPlugins.sln

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration: Release
